# Generated by Django 5.1.6 on 2025-05-06 15:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_profile_photo),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_profile_photo),
        ),
    ]
