"""
Django settings for devguidance_django project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-9lm*)es%5eex%6p+16#0^80)aq-$3^f#uder_zmi03(_e(n6_u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_extensions',
    'drf_spectacular',
    'corsheaders',  # Added for CORS support
    'users',
    'students',
    'mentors',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Added for static files on Vercel
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Comment this out temporarily
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devguidance_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devguidance_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use DATABASE_URL environment variable if available, otherwise use default PostgreSQL config
DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='devguidance'),
            'USER': config('DB_USER', default='myuser'),
            'PASSWORD': config('DB_PASSWORD', default='password'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# Add production URLs for hosted environment
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://devguidance-django.onrender.com",  # Your Render backend URL
    # Add common frontend hosting URLs (update these with your actual frontend URLs)
    "https://devguidance-frontend.vercel.app",
    "https://devguidance-frontend.netlify.app", 
    "https://devguidance.netlify.app",
    "https://devguidance.vercel.app",
]

# For development, you can temporarily allow all origins
# Only enable for development - disable in production for security
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development

CORS_ALLOW_CREDENTIALS = True

# Additional CORS headers needed for API
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Also add to CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'https://devguidance-django.onrender.com',  # Your Render backend URL
    # Add frontend URLs
    'https://devguidance-frontend.vercel.app',
    'https://devguidance-frontend.netlify.app',
    'https://devguidance.netlify.app', 
    'https://devguidance.vercel.app',
]

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# CSRF Configuration for API
CSRF_COOKIE_SECURE = not DEBUG  # Only use secure cookies in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for SPAs
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

# For API endpoints, you might want to exempt some views from CSRF
# This is handled per-view basis with @csrf_exempt decorator

# REST Framework configuration update
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Add this for web browseable API
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # e.g., 1 hour
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY, # Use your project's SECRET_KEY
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# DRF Spectacular Settings for API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'DevGuidance API - Clean & Organized',
    'DESCRIPTION': '''
    # DevGuidance Mentorship Platform API
    
    A **clean, well-organized** REST API for the DevGuidance mentorship platform that connects students with experienced mentors in the tech industry.
    
    ## 🎯 API Organization
    Our API is now **logically organized** without duplicate endpoints:
    
    ### 🔐 **Authentication & User Management** (`/api/users/`)
    - User registration and authentication
    - JWT token management  
    - Real-time messaging system
    - Core user functionality
    
    ### 👨‍🎓 **Student Management** (`/api/students/`)
    - Complete student profile management
    - Project showcase and portfolio
    - Search by technology stack and year level
    - Student statistics and analytics
    
    ### 👨‍🏫 **Mentor Management** (`/api/mentors/`)
    - Comprehensive mentor profiles
    - Expertise-based search and discovery
    - Availability checking
    - Mentorship request management
    
    ### 🔑 **Token Management** (`/api/token/`)
    - JWT token obtain and refresh
    - Secure authentication flow
    
    ## ✨ Key Features
    - **🚫 No Duplicate Endpoints**: Clean, organized API structure
    - **🔍 Advanced Search**: Find mentors by expertise, students by tech stack
    - **💬 Real-time Messaging**: WebSocket-like streaming for conversations
    - **📁 File Uploads**: Profile photos and document attachments
    - **📊 Analytics**: Student and mentor statistics
    - **🔒 Secure**: JWT-based authentication with rate limiting
    
    ## 🚀 Getting Started
    
    ### Authentication Flow:
    1. **Register**: `POST /api/users/register/` (Student or Mentor)
    2. **Login**: `POST /api/token/` (Get JWT tokens)
    3. **Access**: Include `Authorization: Bearer <token>` in headers
    4. **Refresh**: `POST /api/token/refresh/` when token expires
    
    ### For Students:
    - Browse mentors: `GET /api/mentors/browse/`
    - Manage profile: `GET/PUT /api/students/profiles/me/`
    - Create projects: `POST /api/students/projects/`
    - Request mentorship: `POST /api/mentors/mentorship-requests/`
    
    ### For Mentors:
    - Manage profile: `GET/PUT /api/mentors/profiles/me/`
    - View requests: `GET /api/mentors/mentorship-requests/mentor/`
    - Accept/decline: `PATCH /api/mentors/mentorship-requests/{id}/accept/`
    
    ## 🔧 Technical Details
    
    ### Rate Limiting:
    - Registration: 5 requests/minute
    - Token obtain: 5 requests/minute  
    - Token refresh: 10 requests/minute
    
    ### File Uploads:
    - Profile photos: Max 2MB (JPEG/PNG/WebP)
    - Message attachments: Max 5MB (PDF, DOCX, images, etc.)
    
    ### Error Handling:
    Standard HTTP status codes with detailed JSON error messages.
    
    ## 📈 Improvements Made
    - ✅ Removed all duplicate endpoints
    - ✅ Logical separation by domain (students, mentors, users)
    - ✅ Comprehensive documentation with examples
    - ✅ Clear API structure and naming conventions
    - ✅ Enhanced search and discovery features
    ''',
    'VERSION': '2.0.0',  # Updated version to reflect the cleanup
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': True,  # Enable sorting for better organization
    
    # Authentication schemes
    'AUTHENTICATION_SCHEMES': [
        {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    ],
    
    # Security schemes
    'SECURITY': [{'bearerAuth': []}],
    
    # Custom extensions
    'EXTENSIONS_INFO': {
        'x-logo': {
            'url': 'https://example.com/logo.png',
            'altText': 'DevGuidance - Clean API'
        }
    },
    
    # Contact and external docs
    'CONTACT': {
        'name': 'DevGuidance API Support',
        'email': 'support@devguidance.com',
        'url': 'https://devguidance.com/support',
    },
    'LICENSE': {
        'name': 'MIT License',
        'url': 'https://opensource.org/licenses/MIT',
    },
    'EXTERNAL_DOCS': {
        'description': 'DevGuidance Documentation',
        'url': 'https://docs.devguidance.com',
    },
    
    # Enhanced UI customization
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,  # Show operation IDs for better organization
        'defaultModelsExpandDepth': 1,  # Cleaner initial view
        'defaultModelExpandDepth': 1,
        'displayRequestDuration': True,
        'docExpansion': 'list',  # Show all endpoints organized by tags
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tagsSorter': 'alpha',  # Sort tags alphabetically
        'operationsSorter': 'alpha',  # Sort operations alphabetically
    },
    
    # Redoc settings
    'REDOC_UI_SETTINGS': {
        'nativeScrollbars': False,
        'theme': {
            'colors': {
                'primary': {
                    'main': '#1976d2'
                },
                'success': {
                    'main': '#4caf50'
                }
            },
            'typography': {
                'fontSize': '14px',
                'lineHeight': '1.5em',
                'code': {
                    'fontSize': '13px',
                    'fontFamily': 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace'
                }
            }
        },
        'scrollYOffset': 60,
        'hideDownloadButton': False,
        'disableSearch': False,
    },
    
    # Updated tags for clean organization
    'TAGS': [
        {
            'name': 'Authentication',
            'description': '''
            🔐 **User Registration & Authentication**
            
            Complete authentication flow including user registration, login, and JWT token management.
            No duplicate endpoints - all auth functionality consolidated here.
            '''
        },
        {
            'name': 'Users', 
            'description': '''
            👤 **Core User Management**
            
            Essential user functionality including protected endpoints and account management.
            Clean separation from profile-specific operations.
            '''
        },
        {
            'name': 'Students',
            'description': '''
            👨‍🎓 **Student Profile & Projects**
            
            **All student-related functionality in one place:**
            - Profile management and customization
            - Project showcase and portfolio
            - Technology stack tracking
            - Academic year level organization
            - Student statistics and analytics
            '''
        },
        {
            'name': 'Projects',
            'description': '''
            📁 **Student Project Management**
            
            Comprehensive project management for students including creation, 
            editing, and tool-based search functionality.
            '''
        },
        {
            'name': 'Mentors',
            'description': '''
            👨‍🏫 **Mentor Profiles & Management**
            
            **Complete mentor ecosystem:**
            - Professional profile management
            - Expertise and experience tracking
            - Availability status monitoring
            - Mentor discovery and browsing
            '''
        },
        {
            'name': 'Browse',
            'description': '''
            🔍 **Mentor Discovery**
            
            Advanced search and discovery features for students to find the perfect mentors
            based on expertise, experience, and availability.
            '''
        },
        {
            'name': 'Mentorship',
            'description': '''
            🤝 **Mentorship Relationship Management**
            
            **End-to-end mentorship flow:**
            - Request creation and management
            - Accept/decline functionality for mentors
            - Status tracking and updates
            - Relationship analytics
            '''
        },
        {
            'name': 'Messages',
            'description': '''
            💬 **Real-time Communication**
            
            Secure messaging system between mentors and students with file attachment
            support and real-time streaming capabilities.
            '''
        },
        {
            'name': 'Search',
            'description': '''
            🔍 **Advanced Search & Discovery**
            
            Powerful search functionality across students and mentors with filtering
            by technology, expertise, year level, and more.
            '''
        }
    ],
    
    # Preprocessing hooks
    'PREPROCESSING_HOOKS': [
        'drf_spectacular.hooks.preprocess_exclude_path_format'
    ],
    
    # Postprocessing hooks for customization
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums'
    ],
    
    # Enum handling - corrected paths or removed if not needed
    'ENUM_NAME_OVERRIDES': {},
    
    # Component naming
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': False,
    
    # Schema generation
    'DISABLE_ERRORS_AND_WARNINGS': False,
    
    # Additional customizations for clean organization
    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Development server'
        },
        {
            'url': 'https://api.devguidance.com',
            'description': 'Production server'
        }
    ],
}

# Add at the end of settings.py for debugging
if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }

# Temporarily disable CSRF for all views (ONLY FOR DEBUGGING)
USE_CSRF = False
